### ISSUE TITLE
Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead

### ISSUE THREAD

**Issue by siegfried** [DockYard/json_api_assert#30]
Thanks for make such a great mix. It's going well in my project, however, the warnings of deprecation are quite annoying.

```
warning: Mix.Utils.underscore/1 is deprecated, use Macro.underscore/1 instead
  (mix) lib/mix/utils.ex:244: Mix.Utils.underscore/1
  lib/json_api_assert/serializer.ex:61: JsonApiAssert.Serializer.put_type/3
  lib/json_api_assert/serializer.ex:34: JsonApiAssert.Serializer.serialize/2
  test/controllers/api/v1/survey_controller_test.exs:21: Tbn2020.Api.V1.SurveyControllerTest."test GET /api/v1/surveys returns surveys including questions and choices"/1
  (ex_unit) lib/ex_unit/runner.ex:302: ExUnit.Runner.exec_test/1
```

My Elixir and Mix are 1.4.2.

**Comment by siegfried** [comment]
Looks like it is fixed in master branch. Thanks.

**Comment by bcardarella** [comment]
I should probably do a release 😄
